/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convert_ip;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author TOSHIBA-97
 */
public class convert extends javax.swing.JFrame {
DefaultListModel Model = new DefaultListModel();
    /**
     * Creates new form convert
     */
    public convert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JList<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Masukan IP");

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(output);

        jLabel2.setText("Kelas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(68, 68, 68))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // Convert the TCP/IP address string to an integer value
       Model.addElement(null);
        String ip = jTextField1.getText();
        String[] a = ip.split("\\.");        
        Model.removeAllElements();
        int g = 0;
        if(a.length != 4)
        {
            JOptionPane.showMessageDialog(null, "Panjang dari IP tidak boleh lebih dari 4");
            jTextField1.setText(null);
              
        }
        else
        {
         if(ip.endsWith(".") == true | a[0].matches("[a-zA-Z_]+") | a[1].matches("[a-zA-Z_]+") | a[2].matches("[a-zA-Z_]+") | a[3].matches("[a-zA-Z_]+")
               | ip.startsWith(".") == true)
            {
                JOptionPane.showMessageDialog(null, "Inputan tidak boleh huruf");
            }
            else
            {
                int b = Integer.parseInt(a[3]);
                int d = Integer.parseInt(a[2]);
                int e = Integer.parseInt(a[1]);
                int f = Integer.parseInt(a[0]);

                if( b<0 | b>254 | d<0 | d>254 | e<0 | e>254 | f<0 | f>254 )
                {
                    JOptionPane.showMessageDialog(null, "Nilai IP tidak boleh lebih dari 254 atau kurang dari 0");
                    jTextField1.setText(null);
                    
                }
                else
                {      
                   //Perulangan Kelas    
                        if(f<128 && f>=0 | e<128 && e>=0 | d<128 && d>=0 | b<128 && b>=0 ) {
                            jTextField2.setText("Kelas A");
                        } else if(f<192 && f>=128 | e<192 && e>=128 | d<192 && d>=128 | b<192 && b>=128) {
                             jTextField2.setText("Kelas B");
                        } else if(f<224 && f>=192){
                             jTextField2.setText("Kelas C");
                        } else if(f<240 && f>= 224 ){
                             jTextField2.setText("Kelas D");
                        } else if(f>=240) {
                            jTextField2.setText("Kelas E");
                    }
                        //End Perulangan Kelas  
                    
                        int angka1[] = new int[100];
                        int angka2[] = new int[100];
                        int angka3[] = new int[100];
                        int angka4[] = new int[100];
                        int index1 = 0;
                        int index2 = 0;
                        int index3 = 0;
                        int index4 = 0;

                        for (int i=0; 0<f;) 
                               {
                            angka1[index1++] = f%2;
                            f = f/2;
                                   }
                        for (int i=0; 0<e;) 
                               {
                            angka2[index2++] = e%2;
                            e = e/2;
                                   }
                        for (int i=0; 0<d;) 
                               {
                            angka3[index3++] = d%2;
                            d = d/2;
                                   }
                        for (int i=0; 0<b;) 
                               {
                            angka4[index4++] = b%2;
                            b = b/2;
                                   }
                     
                        
                        
  String hasil1 = angka1[7]+""+angka1[6]+""+angka1[5]+""+angka1[4]+""+angka1[3]+""+angka1[2]+""+angka1[1]+""+angka1[0];
  String hasil2 = angka2[7]+""+angka2[6]+""+angka2[5]+""+angka2[4]+""+angka2[3]+""+angka2[2]+""+angka2[1]+""+angka2[0]; 
  String hasil3 = angka3[7]+""+angka3[6]+""+angka3[5]+""+angka3[4]+""+angka3[3]+""+angka3[2]+""+angka3[1]+""+angka3[0];
  String hasil4 = angka4[7]+""+angka4[6]+""+angka4[5]+""+angka4[4]+""+angka4[3]+""+angka4[2]+""+angka4[1]+""+angka4[0]; 
  Model.addElement(hasil1+"."+hasil2+"."+hasil3+"."+hasil4);
                }      
               
          }
            
        }
        
        output.setModel(Model);       
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JList<String> output;
    // End of variables declaration//GEN-END:variables
}
